//created on: 13.10.2015
package de.hdm.bahnhofsteuerung

//list any import classes here.
import de.hdm.bahnhofsteuerung.bahnhof.*;
import de.hdm.bahnhofsteuerung.events.*


//declare any global variables here
declare Zugeinfahrt
	@role(event)
end

declare Zugdurchfahrt
	@role(event)
end

declare Zugabfahrt
	@role(event)
end



rule "Zugeinfahrt bekanntgeben"
	no-loop
    when
        $ze: Zugeinfahrt()
    then
        $ze.getGleis().getAnzeige().anzeigen("Der Zug "+$ze.getZug().getId()
        +" mit dem Ziel "+$ze.getZiel()+" ist eingefahren."); 
end

rule "Zugabfahrt bekanntgeben"
	no-loop
    when
        $za: Zugabfahrt()
        $ze: Zugeinfahrt(zug==$za.zug)
    then
		$za.getGleis().getAnzeige().anzeigen("Der Zug "+$za.getZug().getId()
		+" nach "+$ze.getZiel()+" ist abgefahren");
end

