//created on: 20.01.2016
package de.hdm.drools

//list any import classes here.
import de.hdm.drools.Netzverwaltung;
import de.hdm.drools.resource.*;
import de.hdm.drools.nachricht.*


//declare any global variables here




rule "Your First Rule"

    when
        //conditions
    then
        //actions

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
